# This is a basic workflow to help you get started with Actions

name: neobotix-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "rolling" branch
  push:
    branches: [ "rolling" ]
  pull_request:
    branches: [ "rolling" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: ros-tooling/setup-ros@0.3.4
        with:
          use-ros2-testing: false
      - uses: ros-tooling/action-ros-ci@0.2.6
        with:
          target-ros2-distro: rolling
          colcon-defaults: |
            {
              "build": {
                "symlink-install": true
              }
            }
